services:
    api:
      build: ./app
      environment:
        - DD_SERVICE=${COMPOSE_PROJECT_NAME}-api
        - DD_ENV=${DD_ENV}
        - DD_VERSION=1.0.0
        - DD_AGENT_HOST=datadog
        - DD_TRACE_AGENT_PORT=8126
        - DD_RUNTIME_METRICS_ENABLED=true
        - DD_LOGS_INJECTION=true
        - DD_TRACING_ENABLED=${DD_TRACING_ENABLED}
      links:
        - datadog

    datadog:
      image: datadog/agent:7
      environment:
        - DD_API_KEY=${DD_API_KEY}
        - DD_SITE=${DD_SITE}
        - DD_ENV=${DD_ENV}
        - DD_APM_ENABLED=true
        - DD_LOGS_ENABLED=true
        - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
        - DD_CONTAINER_EXCLUDE="name:datadog-agent"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

    nginx:
        image: nginx:1.27.4
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - api

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-5
        volumes:
            - ./statsd.config.json:/opt/statsd/config/udp.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:11.5.2
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.2
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s" --docker_only=true
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local
