name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'informe.html'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: Install deps
        run: pnpm install --ignore-workspace --lockfile-dir=../

      - name: Build
        run: make pages

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=melodia-docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
